#!/usr/bin/env python3
#::!/bin/python3

from os import system
from sys import argv

try:
	syscode = "echo -n \"Xatolik ro'y berdi.\"\n"
	try:
		file = argv[1]
		fl = '.'.join(file.split('.')[:-1])
		end = file.split('.')[-1]
		#print(file)
		if end == 'asm':
			syscode = f'nasm -f elf64 {file}\nld -o {fl} {fl}.o\nrm {fl}.o\nsudo ./{fl}'
		elif end == 'c':
			print(2)
			syscode = f'gcc {file} -o {fl}\nsudo ./{fl}'
		elif end == 'cpp':
			syscode = f'g++ {file} -o {fl}\nsudo ./{fl}'
	except IndexError:
		argv[100]#syscode += "echo \" Fayl kiritilmadi.\""
	system(syscode)
except IndexError:
	n = 10
	print(f"""
{'-o':<10} Nasm orqali BKF yaratish
{'-i':<10} Image (iso) fayl hosil qilish
{'-c':<10} GCC kompilyatsiya
{'-g':<10} g++ kompilyatsiya
""".strip())
